(() => {
  const $=s=>document.querySelector(s), lang=$('#language'); let state=JSON.parse(localStorage.getItem('historia-state')||'{"learned":[],"wrong":[]}'), view='study', topic='all', quiz=null;
  const topicNames={"sodan-jalkeen":"Sodanjälkeinen Suomi",postwar:'Sodanjälkeinen Suomi',"muutos":'Suomi muuttuu',"hyvinvointi":'Hyvinvointivaltio',eu:'Euroopan unioni',"pohjois-eurooppa":'Pohjoismaat',kertaus:'Kertaus'};
  const save=()=>{localStorage.setItem('historia-state',JSON.stringify(state));$('#saved-count').textContent=state.learned.length?`${state.learned.length} opittua`:''}; const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function wordify(text){return esc(text).split(/(Suomi|Suomessa|Suomesta|Suomen|EU|euro|Pohjoismaat|Skandinavia|koulutus|terveydenhuolto|hyvinvointivaltio|sotakorvaukset|Neuvostoliitto|Ruotsi|Norja|Tanska|Islanti|Viro|Latvia|Liettua|rauha|yhteistyö|elintaso|koulupakko|maaseutu|kaupunki|pula)/gi).map(x=>GLOSSARY[x]?`<button class="word" data-word="${esc(x)}">${esc(x)}</button>`:x).join('')}
  const tr=(x)=>x.translations?.[lang.value]||x.fi;
  function study(){let ls=LESSONS.filter(x=>topic==='all'||x.topic===topic||topicNames[x.topic]===topic);$('#content').innerHTML=ls.length?`<div class="lesson-grid">${ls.map(x=>`<article class="lesson"><span class="topic-label">${topicNames[x.topic]||x.topic}</span><h3>${esc(x.title)}</h3><p>${wordify(x.fi)}</p><div class="lesson-actions"><button class="secondary translate" data-id="${x.id}">Käännä</button><button class="secondary learned ${state.learned.includes(x.id)?'learned':''}" data-id="${x.id}">${state.learned.includes(x.id)?'✓ Opittu':'Merkitse opituksi'}</button></div><div class="translated" hidden>${esc(tr(x))}</div><p class="memory" hidden>Muista: ${esc(x.memory[lang.value]||x.memory.fi)}</p></article>`).join('')}</div>`:'<div class="start-panel"><p>Ei vielä sisältöä tässä aiheessa.</p></div>'; bindStudy()}
  function bindStudy(){document.querySelectorAll('.translate').forEach(b=>b.onclick=()=>{let c=b.closest('.lesson');c.querySelector('.translated').hidden=!c.querySelector('.translated').hidden;c.querySelector('.memory').hidden=c.querySelector('.translated').hidden});document.querySelectorAll('.learned').forEach(b=>b.onclick=()=>{let id=b.dataset.id;state.learned=state.learned.includes(id)?state.learned.filter(x=>x!==id):[...state.learned,id];save();study()});document.querySelectorAll('.word').forEach(b=>b.onclick=()=>translateWord(b.dataset.word))}
  function translateWord(w){let x=GLOSSARY[w]||GLOSSARY[Object.keys(GLOSSARY).find(k=>k.toLowerCase()===w.toLowerCase())];$('#original-word').textContent=w;$('#translated-word').textContent=x?.[lang.value]||'Käännöstä ei ole vielä tallennettu.';$('#translation-note').textContent=x?'Napauta vain silloin, kun sana on vaikea.':'Voit hakea sanan verkosta.';$('#online-translation').href=`https://translate.google.com/?sl=fi&tl=${lang.value}&text=${encodeURIComponent(w)}`;$('#translation').showModal()}
  function practice(){let qs=QUESTIONS.filter(q=>q.type!=='match'&&(topic==='all'||q.topic===topic));quiz=quiz||{qs,at:0,score:0,answered:false}; if(quiz.qs!==qs)quiz={qs,at:0,score:0,answered:false}; renderQuiz()}
  function renderQuiz(){if(!quiz.qs.length){$('#content').innerHTML='<div class="start-panel"><p>Tässä aiheessa ei ole vielä kysymyksiä.</p></div>';return}let q=quiz.qs[quiz.at];if(!q){return result();}$('#content').innerHTML=`<div class="quiz-panel"><div class="quiz-top"><span>Kysymys ${quiz.at+1} / ${quiz.qs.length}</span><span>${quiz.score} oikein</span></div><div class="progress"><div style="width:${(quiz.at/quiz.qs.length)*100}%"></div></div><div class="question">${esc(q.prompt)}</div><div class="options">${q.options.map((o,i)=>`<div class="option" data-i="${i}"><button class="pick" tabindex="-1">${String.fromCharCode(65+i)}</button><span>${esc(o)}</span></div>`).join('')}</div><div id="feedback"></div></div>`;document.querySelectorAll('.option').forEach(o=>o.onclick=()=>answer(+o.dataset.i));}
  function answer(i){if(quiz.answered)return;quiz.answered=true;let q=quiz.qs[quiz.at],ok=i===q.answer;if(ok)quiz.score++;else state.wrong=[...new Set([...state.wrong,q.id])];save();document.querySelectorAll('.option').forEach((o,n)=>{o.classList.add('locked');if(n===q.answer)o.classList.add('correct');if(n===i&&!ok)o.classList.add('wrong')});let l=LESSONS.find(x=>x.id===q.lesson);$('#feedback').innerHTML=`<div class="feedback ${ok?'':'incorrect'}"><h3>${ok?'Hyvä! Oikein.':'Ei haittaa — opitaan tästä.'}</h3><p>${esc(l?.fi||'Katso muistiinpanot ja kokeile uudestaan.')}</p>${l?`<p class="memory">Muista: ${esc(l.memory[lang.value]||l.memory.fi)}</p>`:''}<div class="quiz-actions"><button class="primary" id="next">${quiz.at===quiz.qs.length-1?'Katso tulos':'Seuraava'} <span>→</span></button></div></div>`;$('#next').onclick=()=>{quiz.at++;quiz.answered=false;renderQuiz()}}
  function result(){$('#content').innerHTML=`<div class="quiz-panel"><span class="eyebrow">PIKATESTI VALMIS</span><h2>Hyvä työ.</h2><div class="result-score">${quiz.score} / ${quiz.qs.length}</div><p>${quiz.score===quiz.qs.length?'Kaikki oikein — olet valmis!':'Kertaa vaikeat kohdat muistiinpanoista ja kokeile uudestaan.'}</p><div class="quiz-actions"><button class="primary" id="retry">Yritä uudestaan <span>↗</span></button><button class="secondary" id="to-study">Katso muistiinpanot</button></div></div>`;$('#retry').onclick=()=>{quiz=null;practice()};$('#to-study').onclick=()=>{view='study';document.querySelector('[data-view="study"]').click()}}
  function match(){let q=QUESTIONS.find(x=>x.type==='match'&&(topic==='all'||x.topic===topic))||QUESTIONS.find(x=>x.type==='match');let left=q.pairs.map(x=>x[0]),right=[...q.pairs.map(x=>x[1])].sort(()=>Math.random()-.5),selected=null,linked=0;$('#content').innerHTML=`<div class="quiz-panel"><span class="eyebrow">YHDISTÄ</span><h2>${esc(q.prompt)}</h2><p class="match-hint">Valitse ensin vasemmalta ja sitten oikealta sopiva pari.</p><div class="match-grid"><div class="match-column">${left.map((x,i)=>`<button class="match-item left" data-i="${i}">${esc(x)}</button>`).join('')}</div><div class="match-column">${right.map(x=>`<button class="match-item right" data-x="${esc(x)}">${esc(x)}</button>`).join('')}</div></div><div id="match-feedback"></div></div>`;document.querySelectorAll('.left').forEach(b=>b.onclick=()=>{selected=+b.dataset.i;document.querySelectorAll('.left').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});document.querySelectorAll('.right').forEach(b=>b.onclick=()=>{if(selected===null)return;let correct=q.pairs[selected][1]===b.dataset.x;b.classList.add(correct?'linked':'failed');if(correct){document.querySelectorAll('.left')[selected].classList.add('linked');selected=null;linked++;if(linked===q.pairs.length)$('#match-feedback').innerHTML='<div class="feedback"><h3>Kaikki yhdistetty!</h3><button class="primary" id="again">Uusi yhdistely ↗</button></div>'}else setTimeout(()=>b.classList.remove('failed'),500);$('#again')?.addEventListener('click',match)})}
  function words(){let q=$('#word-search')?.value?.toLowerCase()||'';let entries=Object.entries(GLOSSARY).filter(([k,v])=>!q||k.toLowerCase().includes(q)||(v[lang.value]||'').toLowerCase().includes(q));$('#content').innerHTML=`<input id="word-search" class="word-search" placeholder="Hae sanaa…" value="${esc(q)}"><div class="dictionary">${entries.slice(0,60).map(([k,v])=>`<div class="dictionary-entry"><button class="word" data-word="${esc(k)}"><b>${esc(k)}</b></button><p>${esc(v[lang.value]||'')}</p></div>`).join('')}</div>`;$('#word-search').oninput=words;document.querySelectorAll('.word').forEach(b=>b.onclick=()=>translateWord(b.dataset.word))}
  function render(){if(view==='study')study();else if(view==='practice')practice();else if(view==='exam'){quiz=null;practice()}else if(view==='match'){match()}else words()}
  document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;quiz=null;render()});$('#topic').onchange=e=>{topic=e.target.value;quiz=null;render()};lang.onchange=()=>{save();render()};$('#start').onclick=()=>$('#workspace').scrollIntoView();$('#close-translation').onclick=()=>$('#translation').close();$('#reset').onclick=()=>{if(confirm('Nollataanko oma edistyminen?')){state={learned:[],wrong:[]};save();render()}};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#translation').open)$('#translation').close()});save();render();
})();
