window.GLOSSARY = {
  "Suomi": {fa:"فنلاند",ar:"فنلندا",fr:"Finlande",uk:"Фінляндія",so:"Finland"},
  "Suomessa": {fa:"در فنلاند",ar:"في فنلندا",fr:"en Finlande",uk:"у Фінляндії",so:"Finland gudaheeda"},
  "Suomesta": {fa:"از فنلاند",ar:"من فنلندا",fr:"de Finlande",uk:"з Фінляндії",so:"Finland ka timid"},
  "Suomen": {fa:"فنلاند / متعلق به فنلاند",ar:"فنلندا / الفنلندي",fr:"de la Finlande",uk:"Фінляндії",so:"Finland"},
  "suomalainen": {fa:"فنلاندی",ar:"فنلندي",fr:"finlandais",uk:"фінський",so:"Finish"},
  "suomalaiset": {fa:"فنلاندی‌ها",ar:"الفنلنديون",fr:"les Finlandais",uk:"фіни",so:"dadka Finnishka"},
  "Ruotsi": {fa:"سوئد",ar:"السويد",fr:"Suède",uk:"Швеція",so:"Iswiidhan"},
  "Ruotsiin": {fa:"به سوئد",ar:"إلى السويد",fr:"en Suède",uk:"до Швеції",so:"Iswiidhan"},
  "Ruotsin": {fa:"سوئد / متعلق به سوئد",ar:"السويد / السويدي",fr:"de la Suède",uk:"Швеції",so:"Iswiidhan"},
  "Neuvostoliitto": {fa:"اتحاد شوروی",ar:"الاتحاد السوفيتي",fr:"Union soviétique",uk:"Радянський Союз",so:"Midowgii Soofiyeeti"},
  "Neuvostoliiton": {fa:"اتحاد شوروی / متعلق به شوروی",ar:"للاتحاد السوفيتي",fr:"de l’Union soviétique",uk:"Радянського Союзу",so:"Midowgii Soofiyeeti"},
  "Neuvostoliitolle": {fa:"به اتحاد شوروی",ar:"إلى الاتحاد السوفيتي",fr:"à l’Union soviétique",uk:"Радянському Союзу",so:"Midowgii Soofiyeeti"},
  "sota": {fa:"جنگ",ar:"حرب",fr:"guerre",uk:"війна",so:"dagaal"},
  "sodan": {fa:"جنگ / متعلق به جنگ",ar:"الحرب",fr:"de la guerre",uk:"війни",so:"dagaalka"},
  "sodan jälkeen": {fa:"پس از جنگ",ar:"بعد الحرب",fr:"après la guerre",uk:"після війни",so:"dagaalka ka dib"},
  "jälkeen": {fa:"پس از",ar:"بعد",fr:"après",uk:"після",so:"ka dib"},
  "jatkosota": {fa:"جنگ پس‌آیند",ar:"حرب الاستمرار",fr:"guerre de Continuation",uk:"Війна-продовження",so:"Dagaalkii Sii-socday"},
  "rauha": {fa:"صلح",ar:"سلام",fr:"paix",uk:"мир",so:"nabad"},
  "itsenäisyys": {fa:"استقلال",ar:"استقلال",fr:"indépendance",uk:"незалежність",so:"madax-bannaani"},
  "itsenäinen": {fa:"مستقل",ar:"مستقل",fr:"indépendant",uk:"незалежний",so:"madax-bannaan"},
  "sotakorvaukset": {fa:"غرامت‌های جنگی",ar:"تعويضات الحرب",fr:"réparations de guerre",uk:"воєнні репарації",so:"magdhowga dagaalka"},
  "sotakorvauksia": {fa:"غرامت جنگی",ar:"تعويضات حرب",fr:"des réparations de guerre",uk:"воєнні репарації",so:"magdhow dagaal"},
  "maksoi": {fa:"پرداخت کرد",ar:"دفع",fr:"a payé",uk:"сплатила",so:"bixisay"},
  "maksaa": {fa:"پرداخت کردن",ar:"يدفع",fr:"payer",uk:"платити",so:"bixin"},
  "teollisuus": {fa:"صنعت",ar:"صناعة",fr:"industrie",uk:"промисловість",so:"warshadaha"},
  "teollistui": {fa:"صنعتی شد",ar:"أصبحت صناعية",fr:"s’est industrialisé",uk:"індустріалізувалася",so:"warshadoobay"},
  "tehtaat": {fa:"کارخانه‌ها",ar:"مصانع",fr:"usines",uk:"заводи",so:"warshado"},
  "tuotanto": {fa:"تولید",ar:"إنتاج",fr:"production",uk:"виробництво",so:"wax-soo-saar"},
  "talous": {fa:"اقتصاد",ar:"اقتصاد",fr:"économie",uk:"економіка",so:"dhaqaale"},
  "kasvoi": {fa:"رشد کرد",ar:"نما",fr:"a augmenté",uk:"зросла",so:"koray"},
  "kehittyi": {fa:"توسعه یافت",ar:"تطوّر",fr:"s’est développé",uk:"розвинулася",so:"horumaray"},
  "jälleenrakennus": {fa:"بازسازی",ar:"إعادة الإعمار",fr:"reconstruction",uk:"відбудова",so:"dib-u-dhis"},
  "elintaso": {fa:"سطح زندگی",ar:"مستوى المعيشة",fr:"niveau de vie",uk:"рівень життя",so:"heerka nolosha"},
  "elintaso nousi": {fa:"سطح زندگی بالا رفت",ar:"ارتفع مستوى المعيشة",fr:"le niveau de vie a augmenté",uk:"рівень життя зріс",so:"heerka noloshu kor buu u kacay"},
  "nousi": {fa:"بالا رفت",ar:"ارتفع",fr:"a augmenté",uk:"піднявся",so:"kor u kacay"},
  "pulaa": {fa:"کمبود",ar:"نقص",fr:"pénurie",uk:"нестача",so:"yaraan"},
  "puute": {fa:"کمبود",ar:"نقص",fr:"manque",uk:"брак",so:"la'aan"},
  "ruokaa": {fa:"غذا",ar:"طعام",fr:"nourriture",uk:"їжа",so:"cunto"},
  "asunnoista": {fa:"از خانه‌ها / مسکن",ar:"من المساكن",fr:"de logements",uk:"житла",so:"guryaha"},
  "kodit": {fa:"خانه‌ها",ar:"بيوت",fr:"foyers",uk:"домівки",so:"guryaha"},
  "kotinsa": {fa:"خانه‌هایشان",ar:"بيوتهم",fr:"leurs foyers",uk:"свої домівки",so:"guryahoodii"},
  "evakot": {fa:"تخلیه‌شدگان جنگی",ar:"النازحون",fr:"évacués",uk:"евакуйовані",so:"dadkii la daadgureeyay"},
  "Karjala": {fa:"کارلیا",ar:"كاريليا",fr:"Carélie",uk:"Карелія",so:"Karelia"},
  "karjalaiset": {fa:"کارلیایی‌ها",ar:"الكاريليون",fr:"Caréliens",uk:"карели",so:"dadka Karelia"},
  "menettivät": {fa:"از دست دادند",ar:"فقدوا",fr:"ont perdu",uk:"втратили",so:"waayeen"},
  "väestö": {fa:"جمعیت",ar:"سكان",fr:"population",uk:"населення",so:"dadweyne"},
  "syntyvyys": {fa:"نرخ تولد",ar:"معدل المواليد",fr:"natalité",uk:"народжуваність",so:"dhalashada"},
  "suuret ikäluokat": {fa:"نسل‌های پرجمعیت پس از جنگ",ar:"جيل طفرة المواليد",fr:"baby-boomers",uk:"покоління бебі-буму",so:"jiilkii dhalashada badnaa"},
  "hyvinvointivaltio": {fa:"دولت رفاه",ar:"دولة الرفاه",fr:"État-providence",uk:"держава добробуту",so:"dawladda daryeelka"},
  "hyvinvointivaltiota": {fa:"دولت رفاه",ar:"دولة الرفاه",fr:"l’État-providence",uk:"державу добробуту",so:"dawladda daryeelka"},
  "rakennettiin": {fa:"ساخته شد",ar:"تم بناؤه",fr:"a été construit",uk:"було збудовано",so:"waa la dhisay"},
  "palvelut": {fa:"خدمات",ar:"خدمات",fr:"services",uk:"послуги",so:"adeegyo"},
  "julkiset": {fa:"عمومی",ar:"عامة",fr:"publics",uk:"державні",so:"dadweyne"},
  "terveydenhuolto": {fa:"مراقبت‌های بهداشتی",ar:"رعاية صحية",fr:"soins de santé",uk:"охорона здоров’я",so:"daryeelka caafimaadka"},
  "terveyspalveluja": {fa:"خدمات بهداشتی",ar:"خدمات صحية",fr:"services de santé",uk:"медичні послуги",so:"adeegyo caafimaad"},
  "koulutus": {fa:"آموزش",ar:"تعليم",fr:"éducation",uk:"освіта",so:"waxbarasho"},
  "koulutusta": {fa:"آموزش",ar:"تعليمًا",fr:"de l’éducation",uk:"освіту",so:"waxbarasho"},
  "koulu": {fa:"مدرسه",ar:"مدرسة",fr:"école",uk:"школа",so:"dugsi"},
  "koulupakko": {fa:"اجبار به مدرسه رفتن",ar:"إلزامية المدرسة",fr:"scolarité obligatoire",uk:"обов’язкове навчання",so:"dugsi khasab ah"},
  "oppivelvollisuus": {fa:"آموزش اجباری",ar:"التعليم الإلزامي",fr:"instruction obligatoire",uk:"обов’язкова освіта",so:"waxbarasho khasab ah"},
  "peruskoulu": {fa:"مدرسه جامع / پایه",ar:"المدرسة الأساسية",fr:"école fondamentale",uk:"загальноосвітня школа",so:"dugsiga aasaasiga"},
  "eläke": {fa:"بازنشستگی / مستمری",ar:"معاش تقاعدي",fr:"retraite",uk:"пенсія",so:"hawlgab"},
  "lapsilisä": {fa:"کمک‌هزینه فرزند",ar:"إعانة الطفل",fr:"allocation familiale",uk:"допомога на дитину",so:"kaalmada carruurta"},
  "työttömyysturva": {fa:"بیمه بیکاری",ar:"ضمان البطالة",fr:"allocation chômage",uk:"допомога з безробіття",so:"dammaanadda shaqo-la'aanta"},
  "verot": {fa:"مالیات‌ها",ar:"ضرائب",fr:"impôts",uk:"податки",so:"canshuuraha"},
  "veroilla": {fa:"با مالیات‌ها",ar:"بالضرائب",fr:"avec les impôts",uk:"податками",so:"canshuuraha"},
  "tasa-arvo": {fa:"برابری",ar:"مساواة",fr:"égalité",uk:"рівність",so:"sinnaan"},
  "oikeuksia": {fa:"حقوق",ar:"حقوق",fr:"droits",uk:"права",so:"xuquuq"},
  "naiset": {fa:"زنان",ar:"نساء",fr:"femmes",uk:"жінки",so:"haween"},
  "miehet": {fa:"مردان",ar:"رجال",fr:"hommes",uk:"чоловіки",so:"rag"},
  "samat oikeudet": {fa:"حقوق برابر",ar:"نفس الحقوق",fr:"les mêmes droits",uk:"однакові права",so:"xuquuq isku mid ah"},
  "maaseutu": {fa:"روستا",ar:"ريف",fr:"campagne",uk:"сільська місцевість",so:"miyi"},
  "maalta": {fa:"از روستا",ar:"من الريف",fr:"de la campagne",uk:"із села",so:"miyiga"},
  "kaupunki": {fa:"شهر",ar:"مدينة",fr:"ville",uk:"місто",so:"magaalo"},
  "kaupunkeihin": {fa:"به شهرها",ar:"إلى المدن",fr:"vers les villes",uk:"до міст",so:"magaalooyinka"},
  "muuttivat": {fa:"نقل مکان کردند",ar:"انتقلوا",fr:"ont déménagé",uk:"переїхали",so:"guureen"},
  "muutti": {fa:"نقل مکان کرد",ar:"انتقل",fr:"a déménagé",uk:"переїхав",so:"guuray"},
  "muuttoliike": {fa:"مهاجرت",ar:"هجرة",fr:"migration",uk:"міграція",so:"hijro"},
  "töihin": {fa:"برای کار / سر کار",ar:"إلى العمل",fr:"au travail",uk:"на роботу",so:"shaqo"},
  "työ": {fa:"کار",ar:"عمل",fr:"travail",uk:"робота",so:"shaqo"},
  "työskennellä": {fa:"کار کردن",ar:"يعمل",fr:"travailler",uk:"працювати",so:"shaqayn"},
  "työntekijät": {fa:"کارگران",ar:"عمال",fr:"travailleurs",uk:"працівники",so:"shaqaale"},
  "työpaikkoja": {fa:"فرصت‌های شغلی",ar:"وظائف",fr:"emplois",uk:"робочі місця",so:"shaqooyin"},
  "lähiöt": {fa:"حومه‌های مسکونی",ar:"ضواحي سكنية",fr:"banlieues",uk:"житлові передмістя",so:"xaafadaha duleedka"},
  "kerrostalot": {fa:"ساختمان‌های آپارتمانی",ar:"عمارات سكنية",fr:"immeubles",uk:"багатоповерхівки",so:"dhismayaasha dabaqyada"},
  "presidentti": {fa:"رئیس‌جمهور",ar:"رئيس",fr:"président",uk:"президент",so:"madaxweyne"},
  "Urho Kekkonen": {fa:"اورهو ککونن",ar:"أورهو كيكونن",fr:"Urho Kekkonen",uk:"Урго Кекконен",so:"Urho Kekkonen"},
  "puolueettomuus": {fa:"بی‌طرفی",ar:"حياد",fr:"neutralité",uk:"нейтралітет",so:"dhexdhexaadnimo"},
  "ulkopolitiikka": {fa:"سیاست خارجی",ar:"سياسة خارجية",fr:"politique étrangère",uk:"зовнішня політика",so:"siyaasadda dibadda"},
  "demokratia": {fa:"دموکراسی",ar:"ديمقراطية",fr:"démocratie",uk:"демократія",so:"dimuqraadiyad"},
  "Euroopan unioni": {fa:"اتحادیه اروپا",ar:"الاتحاد الأوروبي",fr:"Union européenne",uk:"Європейський Союз",so:"Midowga Yurub"},
  "EU": {fa:"اتحادیه اروپا",ar:"الاتحاد الأوروبي",fr:"UE",uk:"ЄС",so:"Midowga Yurub"},
  "Eurooppa": {fa:"اروپا",ar:"أوروبا",fr:"Europe",uk:"Європа",so:"Yurub"},
  "Euroopan": {fa:"اروپا / اروپایی",ar:"أوروبا / أوروبي",fr:"de l’Europe",uk:"Європи",so:"Yurub"},
  "unioni": {fa:"اتحادیه",ar:"اتحاد",fr:"union",uk:"союз",so:"midow"},
  "yhteistyötä": {fa:"همکاری",ar:"تعاون",fr:"coopération",uk:"співпраця",so:"iskaashi"},
  "päätöksiä": {fa:"تصمیم‌ها",ar:"قرارات",fr:"décisions",uk:"рішення",so:"go'aanno"},
  "jäsen": {fa:"عضو",ar:"عضو",fr:"membre",uk:"член",so:"xubin"},
  "jäseneksi": {fa:"به‌عنوان عضو",ar:"كعضو",fr:"comme membre",uk:"членом",so:"xubin ahaan"},
  "jäsenvaltioita": {fa:"کشورهای عضو",ar:"دول أعضاء",fr:"États membres",uk:"держави-члени",so:"dalalka xubnaha ah"},
  "liittyi": {fa:"پیوست",ar:"انضم",fr:"a adhéré",uk:"приєдналася",so:"ku biiray"},
  "haki": {fa:"درخواست داد",ar:"تقدّم بطلب",fr:"a demandé",uk:"подала заявку",so:"codsaday"},
  "kansanäänestys": {fa:"همه‌پرسی",ar:"استفتاء",fr:"référendum",uk:"референдум",so:"afti"},
  "äänestivät": {fa:"رأی دادند",ar:"صوّتوا",fr:"ont voté",uk:"проголосували",so:"codeeyeen"},
  "vuonna": {fa:"در سال",ar:"في سنة",fr:"en l’an",uk:"у році",so:"sannadkii"},
  "1995": {fa:"۱۹۹۵",ar:"١٩٩٥",fr:"1995",uk:"1995",so:"1995"},
  "hajosi": {fa:"فروپاشید",ar:"انهار",fr:"s’est dissous",uk:"розпався",so:"burburay"},
  "euro": {fa:"یورو",ar:"يورو",fr:"euro",uk:"євро",so:"yuuro"},
  "euroa": {fa:"یورو",ar:"يورو",fr:"euros",uk:"євро",so:"yuuro"},
  "käteinen": {fa:"پول نقد",ar:"نقد",fr:"espèces",uk:"готівка",so:"lacag caddaan"},
  "setelit": {fa:"اسکناس‌ها",ar:"أوراق نقدية",fr:"billets",uk:"банкноти",so:"waraaqaha lacagta"},
  "kolikot": {fa:"سکه‌ها",ar:"عملات معدنية",fr:"pièces",uk:"монети",so:"qadaadiic"},
  "käyttöön": {fa:"به کار / وارد استفاده",ar:"قيد الاستخدام",fr:"en usage",uk:"у використання",so:"isticmaalka"},
  "otettiin käyttöön": {fa:"به کار گرفته شد",ar:"تم إدخاله للاستخدام",fr:"a été mis en circulation",uk:"було введено в обіг",so:"waa la isticmaalay"},
  "Pohjoismaat": {fa:"کشورهای نوردیک",ar:"دول الشمال",fr:"pays nordiques",uk:"Північні країни",so:"Wadamada Waqooyiga"},
  "Pohjoismaita": {fa:"کشورهای نوردیک",ar:"دول الشمال",fr:"des pays nordiques",uk:"Північні країни",so:"Wadamada Waqooyiga"},
  "Pohjoismaiden": {fa:"کشورهای نوردیک",ar:"لدول الشمال",fr:"des pays nordiques",uk:"Північних країн",so:"Wadamada Waqooyiga"},
  "Pohjoismaiden neuvostossa": {fa:"در شورای نوردیک",ar:"في مجلس الشمال",fr:"au Conseil nordique",uk:"у Північній раді",so:"Golaha Waqooyiga"},
  "Pohjois-Euroopassa": {fa:"در اروپای شمالی",ar:"في شمال أوروبا",fr:"en Europe du Nord",uk:"у Північній Європі",so:"Waqooyiga Yurub"},
  "Skandinavia": {fa:"اسکاندیناوی",ar:"إسكندنافيا",fr:"Scandinavie",uk:"Скандинавія",so:"Iskaandaneefiya"},
  "Baltia": {fa:"کشورهای بالتیک",ar:"دول البلطيق",fr:"pays baltes",uk:"Балтія",so:"Baltiga"},
  "Viro": {fa:"استونی",ar:"إستونيا",fr:"Estonie",uk:"Естонія",so:"Istooniya"},
  "Latvia": {fa:"لتونی",ar:"لاتفيا",fr:"Lettonie",uk:"Латвія",so:"Laatfiya"},
  "Liettua": {fa:"لیتوانی",ar:"ليتوانيا",fr:"Lituanie",uk:"Литва",so:"Lituweeniya"},
  "Norja": {fa:"نروژ",ar:"النرويج",fr:"Norvège",uk:"Норвегія",so:"Noorweey"},
  "Tanska": {fa:"دانمارک",ar:"الدنمارك",fr:"Danemark",uk:"Данія",so:"Denmark"},
  "Islanti": {fa:"ایسلند",ar:"آيسلندا",fr:"Islande",uk:"Ісландія",so:"Iceland"},
  "paljon": {fa:"زیاد",ar:"كثير",fr:"beaucoup",uk:"багато",so:"badan"},
  "yhteistä": {fa:"مشترک",ar:"مشترك",fr:"en commun",uk:"спільного",so:"wadaag"},
  "Kaikissa": {fa:"در همه",ar:"في جميع",fr:"dans tous",uk:"у всіх",so:"dhammaantood"},
  "kaikki": {fa:"همه",ar:"كل",fr:"tous",uk:"усі",so:"dhammaan"},
  "eivät": {fa:"نیستند / نمی‌کنند",ar:"لا",fr:"ne… pas",uk:"не",so:"ma"},
  "ovat": {fa:"هستند",ar:"هم",fr:"sont",uk:"є",so:"waa"},
  "on": {fa:"است",ar:"هو / هي",fr:"est",uk:"є",so:"waa"},
  "oli": {fa:"بود",ar:"كان",fr:"était",uk:"був",so:"ahaa"},
  "mutta": {fa:"اما",ar:"لكن",fr:"mais",uk:"але",so:"laakiin"},
  "ja": {fa:"و",ar:"و",fr:"et",uk:"і",so:"iyo"},
  "tai": {fa:"یا",ar:"أو",fr:"ou",uk:"або",so:"ama"},
  "koska": {fa:"زیرا",ar:"لأن",fr:"parce que",uk:"тому що",so:"sababtoo ah"},
  "siksi": {fa:"بنابراین",ar:"لذلك",fr:"donc",uk:"тому",so:"sidaas darteed"},
  "ennen": {fa:"پیش از",ar:"قبل",fr:"avant",uk:"до",so:"ka hor"},
  "myös": {fa:"همچنین",ar:"أيضًا",fr:"aussi",uk:"також",so:"sidoo kale"},
  "ensimmäinen": {fa:"اولین",ar:"الأول",fr:"premier",uk:"перший",so:"koowaad"},
  "toinen": {fa:"دوم / دیگری",ar:"الثاني / آخر",fr:"deuxième / autre",uk:"другий",so:"labaad / kale"},
  "oikein": {fa:"درست",ar:"صحيح",fr:"correct",uk:"правильно",so:"sax"},
  "väärin": {fa:"غلط",ar:"خطأ",fr:"faux",uk:"неправильно",so:"khalad"},
  "kyllä": {fa:"بله",ar:"نعم",fr:"oui",uk:"так",so:"haa"},
  "ei": {fa:"نه",ar:"لا",fr:"non",uk:"ні",so:"maya"},
  "mikä": {fa:"چه / کدام",ar:"ما / أي",fr:"quel",uk:"що / який",so:"maxay"},
  "miksi": {fa:"چرا",ar:"لماذا",fr:"pourquoi",uk:"чому",so:"sababtee"},
  "milloin": {fa:"چه زمانی",ar:"متى",fr:"quand",uk:"коли",so:"goorma"},
  "maa": {fa:"کشور / زمین",ar:"بلد / أرض",fr:"pays / terre",uk:"країна / земля",so:"dal / dhul"},
  "maat": {fa:"کشورها",ar:"دول",fr:"pays",uk:"країни",so:"dalal"},
  "valtio": {fa:"کشور / دولت",ar:"دولة",fr:"État",uk:"держава",so:"dawlad"},
  "yhteiskunta": {fa:"جامعه",ar:"مجتمع",fr:"société",uk:"суспільство",so:"bulsho"},
  "muutos": {fa:"تغییر",ar:"تغيير",fr:"changement",uk:"зміна",so:"isbeddel"},
  "muuttui": {fa:"تغییر کرد",ar:"تغيّر",fr:"a changé",uk:"змінився",so:"isbeddelay"},
  "nopeasti": {fa:"به‌سرعت",ar:"بسرعة",fr:"rapidement",uk:"швидко",so:"si degdeg ah"},
  "vähitellen": {fa:"به‌تدریج",ar:"تدريجيًا",fr:"progressivement",uk:"поступово",so:"tartiib tartiib"},
  "ihmiset": {fa:"مردم",ar:"الناس",fr:"gens",uk:"люди",so:"dadka"},
  "lapset": {fa:"کودکان",ar:"أطفال",fr:"enfants",uk:"діти",so:"carruur"},
  "vanhukset": {fa:"سالمندان",ar:"كبار السن",fr:"personnes âgées",uk:"літні люди",so:"waayeel"}
};
